# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:

# Global hooks (these can be configured with global pyproject.toml)
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
        - id: isort
-   repo: https://github.com/hakancelikdev/unimport
    rev: 0.12.1
    hooks:
    -   id: unimport
        args:
        -    --ignore-init
        -    -r
        exclude: 'projects/isolate_proto/*'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: debug-statements
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
        exclude: 'projects/isolate_proto/*'


# Monorepo Hooks (e.g. they need to be project specific)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      -  id: mypy
         args:
         -   --ignore-missing-imports
         -   --no-warn-no-return
         -   --check-untyped-defs
         additional_dependencies: []
         exclude: 'test_.*\.py$'
         files: '^projects/adapter'

      -  id: mypy
         args:
         -   --ignore-missing-imports
         -   --no-warn-no-return
         -   --check-untyped-defs
         additional_dependencies: []
         exclude: 'test_.*\.py$'
         files: '^projects/fal'
