repos:
  - repo: 'https://github.com/psf/black'
    rev: 22.6.0
    hooks:
      - id: black
  - repo: 'https://github.com/pre-commit/mirrors-isort'
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: 'https://github.com/hakancelikdev/unimport'
    rev: 0.12.1
    hooks:
      - id: unimport
        args:
          - '--ignore-init'
          - '-r'
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: debug-statements
        exclude: projects/fal/src/fal/packages/isolated_runner.py
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args:
          - '--py37-plus'
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - '--ignore-missing-imports'
          - '--no-warn-no-return'
          - '--check-untyped-defs'
        additional_dependencies: []
        exclude: test_.*\.py$
        files: ^projects/adapter
      - id: mypy
        args:
          - '--ignore-missing-imports'
          - '--no-warn-no-return'
          - '--check-untyped-defs'
        additional_dependencies: []
        exclude: test_.*\.py$
        files: ^projects/fal
